#!/bin/bash

notification_id=777

if [ ! -f "/tmp/screen_color.conf" ];then
	SCREEN_COLOR=4000
	echo 4000 > /tmp/screen_color.conf
else
	echo "Reading..."
	SCREEN_COLOR=$(cat /tmp/screen_color.conf)
fi

if [ $SCREEN_COLOR -lt 8000 ];then
	SCREEN_COLOR=$(($SCREEN_COLOR+100))
fi

echo $SCREEN_COLOR > /tmp/screen_color.conf
redshift -PO $SCREEN_COLOR

PERCENT=$((($SCREEN_COLOR-2000)/60))
echo $PERCENT

notify-send.sh -r $notification_id -h int:value:$PERCENT -u low " $(cat /tmp/screen_color.conf)K"
py3-cmd refresh redshift
