#!/bin/bash

notification_id=777

SCREEN_COLOR=6500

echo $SCREEN_COLOR > /tmp/screen_color.conf
redshift -PO $SCREEN_COLOR

dunstify -r $notification_id -h int:value:75 -u low " $(cat /tmp/screen_color.conf)K"
PIDS=`ps -ef |grep py3-cmd |grep -v grep | awk '{print $2}'`
if [ "$PIDS" == "" ]; then
	py3-cmd refresh redshift
fi