#!/bin/bash

notification_id=777

if [ ! -f "/tmp/screen_color.conf" ];then
	SCREEN_COLOR=4000
	echo 4000 > /tmp/screen_color.conf
else
	echo "Reading..."
	SCREEN_COLOR=$(cat /tmp/screen_color.conf)
fi

if [ $SCREEN_COLOR -gt 2000 ];then
	SCREEN_COLOR=$(($SCREEN_COLOR-100))
fi

echo $SCREEN_COLOR > /tmp/screen_color.conf
redshift -PO $SCREEN_COLOR

PERCENT=$((($SCREEN_COLOR-2000)/60))
echo $PERCENT

dunstify -r $notification_id -h int:value:$PERCENT -u low " $(cat /tmp/screen_color.conf)K"
PIDS=`ps -ef |grep py3-cmd |grep -v grep | awk '{print $2}'`
if [ "$PIDS" == "" ]; then
	py3-cmd refresh redshift
fi