#!/usr/bin/env bash

if [[ -f "$HOME/.cache/i3lock/current/l_dim.png" ]]; then
	~/.i3/betterlockscreen -l dimblur # dim pixel
else
	echo "Preparing background..."
fi


LCK=/tmp/betterlockscreen.lck
if [ -e $LCK ]; then
	echo "$LCK exists."
else
	echo "Updating background..."
	touch $LCK
	~/.i3/betterlockscreen -u "$HOME/Pictures/Wallpapers/Views"
	rm $LCK
fi