#!/bin/bash

# convert DjVu -> PDF
# usage:  djvu2pdf.sh  <file.djvu>

MY_SAVEIFS=$IFS
#IFS=$(echo -en "\n\b")
IFS=$'\n'

i="$1"
echo "Converting $i to PDF...";
o=$(basename $i .djvu)
o="$o".pdf

tmp=$(date +%H:%M:%S-%m%d%y)
tmp_i=/tmp/ddjvu_"$tmp".djvu
tmp_o=/tmp/ddjvu_"$tmp".pdf
cp $i $tmp_i
ddjvu -format=pdf -quality=85 $tmp_i $tmp_o
mv $tmp_o $o
echo "Done!";

IFS=$MY_SAVEIFS