#!/bin/bash

MY_SAVEIFS=$IFS
#IFS=$(echo -en "\n\b")
IFS=$'\n'

for file in `ls $1`
do
	filename=$(basename "$file")
	extension="${filename##*.}"
	if [ "$extension" = "djvu" ]; then
		echo $file
		o=$(basename $file .djvu)
		o="$o".pdf
		if [ -e $o ]; then
			echo "Done!"
		else
			tmp=$(date +%H:%M:%S-%m%d%y)
			tmp_i=/tmp/ddjvu_"$tmp".djvu
			tmp_o=/tmp/ddjvu_"$tmp".pdf
			cp $file $tmp_i
			ddjvu -format=pdf -quality=85 $tmp_i $tmp_o
			mv $tmp_o $o
			echo "Done!"
		fi
	fi
done

IFS=$MY_SAVEIFS