#!/bin/bash

LCK=/tmp/break_pomodoro.lck
SHOW=/tmp/show_pomodoro.lck
INFO=/tmp/info_pomodoro.lck
STOP=/tmp/stop_pomodoro.lck
STAT=/tmp/stat_pomodoro.lck
ASKZ=/tmp/ask_pomodoro.lck
WORK_TIME=/tmp/work_pomodoro.dat
BREAK_TIME=/tmp/break_pomodoro.dat

if (( $# > 0)); then
	case $1 in
		'show')
			if [ -e $SHOW ]; then
				STR=" "
			else
				STR=" "
			fi;;
		'stat')
			if [ -e $STAT ]; then
				STR+=" #$(cat $STAT)"
			else
				STR+=" #"
			fi;;
		'ask')
			if [ -e $ASKZ ]; then
				STR+=" "
			else
				STR+=" "
			fi;;
		'stop')
			if [ -e $STOP ]; then
				STR+=" "
			else
				STR+=" "
			fi;;
		'info')
			if [ ! -e $INFO ]; then
				echo '  pomodoro' > $INFO
			fi
			if [ -e $LCK ]; then
				STR="$(cat $INFO | sed 's/Time //')"
			else
				STR='  pomodoro'
			fi;;
	esac
else
	if [ -e $SHOW ]; then
		STR=" "
	else
		STR=" "
	fi
	if [ -e $STAT ]; then
		STR+=" #$(cat $STAT)"
	else
		STR+=" #"
	fi
	if [ -e $ASKZ ]; then
		STR+=" "
	else
		STR+=" "
	fi
	if [ -e $STOP ]; then
		STR+=" "
	else
		STR+=" "
	fi
fi
echo $STR