#!/bin/bash

notification_id=728
topple_id=718
dursec=1
((duration=dursec*1000))

LCK=/tmp/break_pomodoro.lck
SHOW=/tmp/show_pomodoro.lck
INFO=/tmp/info_pomodoro.lck
STOP=/tmp/stop_pomodoro.lck
SWAP=/tmp/swap_pomodoro.lck
STAT=/tmp/stat_pomodoro.lck
ASKZ=/tmp/ask_pomodoro.lck

case $1 in
	'show')
		if [ -e $SHOW ]; then
			rm $SHOW
			STR=" "
			dunstify -C $notification_id
			dunstify -r $topple_id -u normal -t $duration ' Pomodoro Display Off'
		else
			touch $SHOW
			STR=" "
			if [[ ! -e $LCK ]]; then
				dunstify -r $topple_id -u low -t $duration ' Pomodoro Display On'
			else
				dunstify -C $topple_id
			fi
		fi;;
	'stop')
		if [ -e $STOP ]; then
			rm $STOP
			STR=" "
			if [ ! -e $LCK -o ! -e $SHOW ]; then
				dunstify -r $topple_id -u low -t $duration ' Pomodoro Resumed'
			fi
		else
			touch $STOP
			STR=" "
			if [ ! -e $LCK -o ! -e $SHOW  ]; then
				dunstify -r $topple_id -u normal -t $duration ' Pomodoro Paused'
			fi
		fi;;
	'swap')
		if cat $INFO | grep Work
		then
			echo Break > $SWAP
		else
			echo Work > $SWAP
		fi;;
	'ask')
		if [ -e $ASKZ ]; then
			rm $ASKZ
			STR=" "
			dunstify -r $topple_id -u normal -t $duration ' Pomodoro Reminder Off'
		else
			touch $ASKZ
			STR=" "
			dunstify -r $topple_id -u low -t $duration ' Pomodoro Reminder On'
		fi;;
	'quit')
		dunstify -r $topple_id -u normal -t $duration ' Pomodoro Quitted'
		if [ -e $LCK ]; then
			rm $LCK
		fi
		if [ -e $STAT ]; then
			rm $STAT
		fi
		dunstify -C $notification_id;;
	'stat')
		if [ -e $STAT ]; then
			STR=" #$(cat $STAT)"
		else
			STR=" #"
		fi;;
esac

py3-cmd refresh external_script
echo $STR