#!/bin/bash

notification_id=728
SHOW=/tmp/show_pomodoro.lck
STOP=/tmp/stop_pomodoro.lck
SWAP=/tmp/swap_pomodoro.lck
WORK_TIME=/tmp/work_pomodoro.dat

if [ ! -e $WORK_TIME ]; then
	TOTAL=1500
	echo $TOTAL > $WORK_TIME
else
	TOTAL=$(cat $WORK_TIME)
fi
if (( $# > 0)); then
	TOTAL=$(($1 * 60))
	echo $TOTAL > $WORK_TIME
fi

if [ ! -e $SHOW ]; then
	touch $SHOW
fi

if [ -e $STOP ]; then
	rm $STOP
fi

echo Work > $SWAP
~/.i3/send_pomodoro