#!/bin/bash

notification_id=777

pactl set-sink-mute 0 0
if [ $(pamixer --get-volume) -lt 120 ]; then
	if [ $# -eq 0 ]; then
		pactl set-sink-volume 0 +1%
	else
		pactl set-sink-volume 0 +$1%
	fi
fi

py3-cmd refresh volume_status
notify-send.sh -r $notification_id -u low " $(pamixer --get-volume)% "
~/.i3/beep