#!/bin/bash

notification_id=777
VOL=$(python ~/.i3/bluevol.py)

if [ $VOL -lt 0 ]; then
	if [ $# -eq 0 ]; then
		pactl set-sink-mute 0 toggle
	else
		pactl set-sink-mute 0 $1
	fi

	py3-cmd refresh volume_status
	~/.i3/beep

	if pamixer --get-mute
	then
		notify-send.sh -r $notification_id -h int:value:$(pamixer --get-volume) -u normal " $(pamixer --get-volume)% ✗"
	else
		notify-send.sh -r $notification_id -h int:value:$(pamixer --get-volume) -u low " $(pamixer --get-volume)% "
		~/.i3/beep
	fi
else
	if [ $VOL -gt 0 ]; then
		echo $VOL > /tmp/bluevol
		python ~/.i3/bluevol.py 0
		notify-send.sh -r $notification_id -h int:value:$VOL -u normal " $VOL% ✗"
	else
		VOL=$(cat /tmp/bluevol)
		python ~/.i3/bluevol.py $VOL
		notify-send.sh -r $notification_id -h int:value:$VOL -u low " $VOL% "
		~/.i3/beep
	fi
fi