#!/bin/bash

tag=$(cmus-remote -Q | grep tag | head -n 3 | sort -r | cut -d ' ' -f 3- | tr '\n' ' ')
pos=$(cmus-remote -Q | grep position | cut -d ' ' -f 2-)
len=$(cmus-remote -Q | grep duration | cut -d ' ' -f 2-)
((m1=pos/60, s1=pos%60, m2=len/60, s2=len%60))

cmus_notification_id=778
if [ "$(cmus-remote -Q | grep status)" == "status paused" ]; then
	dunstify -r $cmus_notification_id " $tag" "$(printf "♪ %d:%02d/%d:%02d ♪" $m1 $s1 $m2 $s2)"
elif [ "$(cmus-remote -Q | grep status)" == "status playing" ]; then
	dunstify -r $cmus_notification_id " $tag" "$(printf "♪ %d:%02d/%d:%02d ♪" $m1 $s1 $m2 $s2)"
elif [ "$(cmus-remote -Q | grep status)" == "status stopped" ]; then
	dunstify -r $cmus_notification_id " $tag" "$(printf "♪ %d:%02d/%d:%02d ♪" $m1 $s1 $m2 $s2)"
fi