#!/bin/bash

notification_id=777
VOL=$(python ~/.i3/bluevol.py)

if [ $VOL -lt 0 ]; then
	if [ $# -eq 0 ]; then
		pactl set-sink-mute 0 toggle
	else
		pactl set-sink-mute 0 $1
	fi

	PIDS=`ps -ef |grep py3-cmd |grep -v grep | awk '{print $2}'`
	if [ "$PIDS" == "" ]; then
		py3-cmd refresh volume_status
	fi
	~/.i3/beep

	if pamixer --get-mute
	then
		dunstify -r $notification_id -h int:value:$(pamixer --get-volume) -u normal " $(pamixer --get-volume)% ✗"
	else
		dunstify -r $notification_id -h int:value:$(pamixer --get-volume) -u low " $(pamixer --get-volume)% "
		~/.i3/beep
	fi
else
	if [ $VOL -gt 0 ]; then
		echo $VOL > /tmp/bluevol
		python ~/.i3/bluevol.py 0
		dunstify -r $notification_id -h int:value:$VOL -u normal "ⓑ $VOL% ✗"
	else
		VOL=$(cat /tmp/bluevol)
		python ~/.i3/bluevol.py $VOL
		dunstify -r $notification_id -h int:value:$VOL -u low "ⓑ $VOL% "
		~/.i3/beep
	fi
fi