#!/bin/bash

notification_id=777

if [ $(pamixer --get-volume) -gt 0 ]; then
	if [ $# -eq 0 ]; then
		pactl set-sink-volume 0 -1%
	else
		pactl set-sink-volume 0 -$1%
	fi
fi

py3-cmd refresh volume_status
notify-send.sh -r $notification_id -u low " $(pamixer --get-volume)% "
~/.i3/beep