#!/bin/bash

notification_id=777

if [ $(pamixer --get-volume) -gt 0 ]; then
	if [ $# -eq 0 ]; then
		pactl set-sink-volume 0 -1%
	else
		pactl set-sink-volume 0 -$1%
	fi
fi

py3-cmd refresh volume_status
if pamixer --get-mute
then
	notify-send.sh -r $notification_id -h int:value:$(pamixer --get-volume) -u normal " $(pamixer --get-volume)% ✗"
else
	notify-send.sh -r $notification_id -h int:value:$(pamixer --get-volume) -u low " $(pamixer --get-volume)% "
fi
~/.i3/beep