#!/bin/bash

notification_id=728
SHOW=/tmp/show_pomodoro.lck
STOP=/tmp/stop_pomodoro.lck
SWAP=/tmp/swap_pomodoro.lck
BREAK_TIME=/tmp/break_pomodoro.dat

if [ ! -e $BREAK_TIME ]; then
	TOTAL=300
	echo $TOTAL > $BREAK_TIME
else
	TOTAL=$(cat $BREAK_TIME)
fi
if (( $# > 0)); then
	TOTAL=$(($1 * 60))
	echo $TOTAL > $BREAK_TIME
fi

if [ ! -e $SHOW ]; then
	touch $SHOW
fi

if [ -e $STOP ]; then
	rm $STOP
fi

echo Break > $SWAP
~/.i3/send_pomodoro