#!/bin/bash

notification_id=777

VOL=$(python ~/.i3/bluevol.py)

if [ $VOL -lt 0 ]; then
	pactl set-sink-mute 0 0
	if [ $(pamixer --get-volume) -lt 127 ]; then
		if [ $# -eq 0 ]; then
			pactl set-sink-volume 0 +1%
		else
			pactl set-sink-volume 0 +$1%
		fi
	fi
	PIDS=`ps -ef | grep py3-cmd | grep -v grep | awk '{print $2}'`
	if [ "$PIDS" == "" ]; then
		py3-cmd refresh volume_status
	fi
	dunstify -r $notification_id -h int:value:$(pamixer --get-volume) -u low " $(pamixer --get-volume)% "
else
	MAC=`bluetoothctl info | awk 'index($1,"Device") {print $2}'`
	DEV=`bluetoothctl info | awk 'index($1,"Name") {print $2}'`
	if [ -e /tmp/bluevol ]; then
		VOL=$(cat /tmp/bluevol)
	fi
	if [ $VOL -lt 127 ]; then
		VOL=$((VOL+1))
		python ~/.i3/bluevol.py $VOL
	fi
	echo $VOL > /tmp/bluevol
	dunstify -r $notification_id -h int:value:$VOL -u low "ⓑ $DEV $VOL%"
fi

~/.i3/beep