#!/bin/bash

# pathList=(".")
# for p in ${pathList[*]}
# do
# 	find $p -type f -name '[^.]*' > $DIR/temp.txt
# done

# for f in `cat $DIR/temp.txt`
# do
# 	# mv $f ${f/\.sh/}
# 	echo $f
# done
if [ -f "${1}" ]; then

	DIR=/tmp/trackize
	if [ ! -e $DIR ]; then
		mkdir $DIR
	fi

	echo $1 > $DIR/mp3name.txt
	sed -i -r "s/([a-zA-Z0-9]) ([a-zA-Z0-9])/\1\_\2/g" $DIR/mp3name.txt
	RidList=("\[" "\]" "[()（）【】《》「」『』]" '"' "[:：／&　]" "\.mp3")
	for p in ${RidList[*]}
	do
		sed -i "s/${p}/ /g" $DIR/mp3name.txt
	done
	opencc -i $DIR/mp3name.txt -o $DIR/mp3name -c t2s.json

	INFO=$(cat $DIR/mp3name | tr -s [:space:] | sed 's/^[ ]*//g; s/^[ ]*//g')
	echo $INFO | sed 's/ /\n/g; s/_/ /g' > $DIR/items.txt
	# cat $DIR/mp3name.txt

	SEL=$(zenity --entry --width=300 --title="${1}" --text="Album: 0 - Æ\t1 - 中\t2 - あ\n$(echo $INFO | sed 's/^/1.\t/; s/ /\n2.\t/; s/ /\n3.\t/; s/ /\n4.\t/; s/ /\n5.\t/; s/ /\n6.\t/; s/ /\n7.\t/; s/ /\n8.\t/; s/ /\n9.\t/; s/_/ /g')")
	case ${SEL:0:1} in
		0) ALBUM=English;;
		1) ALBUM=China;;
		2) ALBUM=Japan;;
	esac
	ARTIST=$(cat $DIR/items.txt | sed -n ''${SEL:1:1}'p')
	TITLE=$(cat $DIR/items.txt | sed -n ''${SEL:2:1}'p')

	if zenity --question --width=300 --title="${1}" --text="Artist - ${ARTIST}\n Title - ${TITLE}\n Album - ${ALBUM}"
	then
		NEW="${HOME}/Music/Songs/${ALBUM}/${TITLE}.mp3"
		if [ ! -f "${NEW}" ]; then
			mid3v2 -t "${TITLE}" -a "${ARTIST}" -A "${ALBUM}" "${1}"
			mv "${1}" "${NEW}"
			TEXT=$(mid3v2 -l "${NEW}")
			zenity --info --width=300 --text="${TEXT}"
		else
			zenity --error --width=300 --text="${NEW} already exists. Please rename."
		fi

	else
		ARTIST=$(zenity --entry --width=300 --title="${FILE}" --text="Artist" --entry-text="${ARTIST}")
		TITLE=$(zenity --entry --width=300 --title="${FILE}" --text="Title" --entry-text="${TITLE}")
		if zenity --question --width=300 --title="${FILE}" --text="Artist - ${ARTIST}\n Title - ${TITLE}\n Album - ${ALBUM}"
		then
			NEW="${HOME}/Music/Songs/${ALBUM}/${TITLE}.mp3"
			if [ ! -f "${NEW}" ]; then
				mid3v2 -t "${TITLE}" -a "${ARTIST}" -A "${ALBUM}" "${1}"
				mv "${1}" "${NEW}"
				TEXT=$(mid3v2 -l "${NEW}")
				zenity --info --width=300 --text="${TEXT}"
			else
				zenity --error --width=300 --text="${NEW} already exists. Please rename."
			fi
		else
			zenity --error --width=300 --text="Operation is canceled."
		fi
	fi

else
	zenity --error --width=300 --text="File ${1} does not exists."
fi